return {

    rank_hierarchy = {
        ["Owner"] = 3,
        ["Exyn Supporter"] = 2,
        ["Exyn User"] = 1
    },
    

    ["owner_hwid_1"] = {
        rank = "Owner",
        color = Color3.fromRGB(255, 0, 0) 
    },
    ["owner_hwid_2"] = {
        rank = "Owner", 
        color = Color3.fromRGB(255, 0, 0)
    },
    ["supporter_hwid_1"] = {
        rank = "Exyn Supporter",
        color = Color3.fromRGB(255, 165, 0)
    },
    ["supporter_hwid_2"] = {
        rank = "Exyn Supporter",
        color = Color3.fromRGB(255, 165, 0)
    }
}
